#!/usr/bin/perl

use strict;
use warnings;

my @required = qw(preserver sunscreen water_bottle jacket);
my @skipper = qw(blue_shirt hat jacket preserver sunscreen);
my @gilligan = qw(red_shirt hat lucky_socks water_bottle);

for my $item (@required) {
    unless (grep { $_ eq $item } @skipper) { print "skipper missing $item\n" };
}

sub check_req_items {
    my ($who) = @_;
    my @required = qw(preserver sunscreen water_bottle jacket);
    for my $item (@required) {
        unless (grep { $_ eq $item } @_) { print "$who is missing $item\n" };
    }
}


check_req_items("gilligan", @gilligan);
