#!/usr/bin/perl

use strict;
use warnings;

{ package Animal;
    sub speak {
        my $class = shift;
        print "a $class goes ", $class->sound, "\n";
    }
}

{ package Cow;
    @Cow::ISA = qw(Animal);
    sub sound { "moo" };
}
{ package Horse;
    @Horse::ISA = qw(Animal);
    sub sound { "neigh" };
}
{ package Sheep;
    @Sheep::ISA = qw(Animal);
    sub sound { "baah" };
}

{ package Mouse;
    @Mouse::ISA = qw(Animal);
    sub sound { "squeak" }
    sub speak {
        my $class = shift;
        $class->SUPER::speak;
        print "[but you can barely hear it!]\n";
    }
}



Cow->speak;
Horse->speak;
Sheep->speak;
Mouse->speak;
