#!/usr/bin/perl

use strict;
use warnings;

use Time::HiRes qw(tv_interval gettimeofday);
use LWP::UserAgent;

my $ua = LWP::UserAgent->new(agent=>"eloggo nickel 54.2");
my $t0 = [gettimeofday()];
my $response = $ua->get("http://center.softland.ru");
my $delta = tv_interval($t0, [gettimeofday]);

my $text = $response->content;

print $text;
print $delta."\n";
