#!/usr/bin/perl

use strict;
use warnings;

my %srv = (
    http => 80,
    smtp => 25,
    pop => 110,
    ssh => 22,
    https => 443,
);

my $srv_ref = \%srv;

print "http port is $srv_ref->{ 'http' }\n";
